- name: Allow HTTP traffic
  gce_net:
    fwname: all-http
    name: default
    allowed: tcp:80;tcp:22
    project_id: "{{ gci.project_id }}"
    credentials_file: "{{ gci.credentials_file }}"
    service_account_email: "{{ gci.service_account_email }}"
