- name: Launch Compute Engine instance
  gce:
    instance_names: "{{ gci.instance_names }}"
    zone: "{{ gci.zone }}"
    machine_type: "{{ gci.machine_type }}"
    image: "{{ gci.image }}"
    state: present
    service_account_email: "{{ gci.service_account_email }}"
    credentials_file: "{{ gci.credentials_file }}"
    project_id: "{{ gci.project_id }}"
    disk_size: 20
