- name: Launch Compute Engine instance
  gce:
    instance_names: "{{ gci.instance_names }}"
    zone: "{{ gci.zone }}"
    machine_type: "{{ gci.machine_type }}"
    image: "{{ gci.image }}"
    state: present
    service_account_email: "{{ gci.service_account_email }}"
    credentials_file: "{{ gci.credentials_file }}"
    project_id: "{{ gci.project_id }}"
    disk_size: 20
    metadata : '{ "startup-script" : "apt-get update" }'
  register: gcei
  notify: Save host data

- name: Wait for SSH to come up
  wait_for:
    delay: 1
    host: "{{ item.public_ip }}"
    port: 22
    timeout: 30
    state: started
  with_items: "{{ gcei.instance_data }}"
