- name: Compute Engine instanse
  hosts: localhost
  tasks:
  - name: Create Instance
    gce:
      instance_names: task1
      zone: europe-west1-b
      machine_type: n1-highcpu-2
      image: ubuntu-1604
      state: present
      service_account_email: "google-cloud-ansible@YOUR_PROJECT_ID.iam.gserviceaccount.com"
      credentials_file: "google-cloud-ansible.json"
      project_id: "YOUR_PROJECT_ID""YOUR_PROJECT_ID"
      disk_size: 20
